### ISSUE TITLE
No proper error message if HEAP_SIZE is not defined

### ISSUE THREAD

**Issue by mrquincle** [dobots/bluenet#37]
An undefined HEAP_SIZE leads to empty value in conf/nRF51822-softdevice.ld and subsequently a linker problem w.r.t. syntax.

It should be captured before that moment and yield an understandable error message.

**Comment by eggerdo** [comment]
This should not happen anymore, if there is no HEAP_SIZE defined in the CMakeBuild.config it takes the value from the CMakeBuild.config.default. More precisely, for any variable that is not defined in the CMakeBuild.config it will take the value from the CMakeBuild.config.default

Can you explain a bit more how this happened? On which branch were you working? what did you try to build? and do you have the BLUENET_DIR environment variable set correctly?

**Comment by mrquincle** [comment]
I just checked it out again (master branch) without merging from my repos to confirm. Just remove HEAP_SIZE from CMakeBuild.config and see for yourself. Yes, I have BLUENET_DIR set.

**Comment by eggerdo** [comment]
ahhh, that change with taking the values from the default did not make it into the master :( sorry for that. I will fix that.

but both bart and me are now mainly working on the sdk_8 branch for the 32k versions, so that's basically the new master. You could try building the sdk8_branch instead, but you will need softdevice s110_8.0 or s130_1.0.0 plus nrf sdk 8.0 for that.

**Comment by eggerdo** [comment]
This should be solved by commit ef294c2ddd4

**Comment by mrquincle** [comment]
Thanks!
